const SOURCE = "Klett: Aspekte neu C1, Kapitelwortschatz";

const profile = (objectives, vocabulary, structures, speakingTask, writingTask) => ({
  objectives,
  vocabulary,
  vocabularySource: SOURCE,
  structures,
  mastery: [
    "Ich kann die drei Lernziele ohne vorbereiteten Mustertext erfüllen.",
    "Ich verwende mindestens fünf Zielwörter und eine C1-Struktur korrekt in einer freien Antwort.",
  ],
  homework: [
    { type: "Mündlich", task: speakingTask },
    { type: "Schriftlich", task: writingTask },
  ],
});

const review = (chapterTitle, grammar, vocabulary) => profile(
  [
    "Ich wiederhole den aktiven Wortschatz aus dem Kapitel „" + chapterTitle + "“ in neuen Kontexten.",
    "Ich wende " + grammar + " in freiem Sprechen und Schreiben sicher an.",
    "Ich erkenne meine wiederkehrenden Fehler und verbessere sie selbstständig.",
  ],
  vocabulary,
  [grammar, "Fehlerkorrektur: Fehler erkennen, begründen und natürlich neu formulieren"],
  "Nimm eine zweiminütige Zusammenfassung zum Kapitel auf und verwende mindestens sechs Zielwörter.",
  "Schreibe zehn abwechslungsreiche Sätze zur Kapitelgrammatik und überarbeite sie anschließend.",
);

const chapterGroupA = [
  [
    profile(
      [
        "Ich verstehe Aufbau und Pointe kurzer Alltagsgeschichten.",
        "Ich erzähle ein Erlebnis chronologisch und anschaulich.",
        "Ich stelle passende Rückfragen zu persönlichen Erfahrungen.",
      ],
      [
        ["der Tagebucheintrag", "ein datierter Text über persönliche Erlebnisse"],
        ["der Scheidungsgrund", "der Anlass für die Auflösung einer Ehe"],
        ["einvernehmlich", "von allen Beteiligten gemeinsam akzeptiert"],
        ["zueinander", "in einer gegenseitigen Beziehung"],
        ["eine Begründung angeben", "einen Grund nachvollziehbar nennen"],
        ["der Gutenachtkuss", "ein Kuss vor dem Einschlafen"],
        ["das Kinderzimmer", "ein Zimmer, das für Kinder eingerichtet ist"],
        ["das Stofftier", "ein weiches Spielzeug in Tierform"],
      ],
      ["zuerst – daraufhin – schließlich", "Was mich daran überrascht hat, war …"],
      "Erzähle eine kurze Alltagsgeschichte mit Anfang, Wendepunkt und Schluss.",
      "Schreibe einen Tagebucheintrag von etwa 100 Wörtern über ein unerwartetes Erlebnis.",
    ),
    profile(
      [
        "Ich fasse unterschiedliche Aussagen zum Zeitempfinden zusammen.",
        "Ich vergleiche objektive Zeit mit subjektivem Zeitgefühl.",
        "Ich drücke Folgen mit passenden Konnektoren aus.",
      ],
      [
        ["das Zeitgefühl", "die subjektive Wahrnehmung von Zeit"],
        ["der Zeitdruck", "das Gefühl, für Aufgaben zu wenig Zeit zu haben"],
        ["die Entschleunigung", "die bewusste Verringerung des Lebenstempos"],
        ["die Zeitverschwendung", "eine wenig sinnvolle Nutzung von Zeit"],
        ["der Wandel", "eine deutliche Veränderung über längere Zeit"],
        ["der Zeitgeist", "typische Denkweise und Stimmung einer Epoche"],
        ["das Zeitempfinden", "die persönliche Wahrnehmung der Zeitdauer"],
        ["die Lebensspanne", "der Zeitraum zwischen Geburt und Tod"],
      ],
      ["demnach / somit / folglich", "Mir kommt die Zeit besonders kurz oder lang vor, wenn …"],
      "Vergleiche zwei Situationen, in denen Zeit unterschiedlich schnell zu vergehen scheint.",
      "Schreibe etwa 120 Wörter zum Thema Umgang mit Zeitdruck.",
    ),
    profile(
      [
        "Ich verstehe Aufgaben und Bedeutung von Vereinen.",
        "Ich stelle Argumente für und gegen eine Mitgliedschaft gegenüber.",
        "Ich überzeuge eine Person mit geordneten Argumenten und Beispielen.",
      ],
      [
        ["der oder die Gleichgesinnte", "eine Person mit ähnlichen Interessen oder Überzeugungen"],
        ["einem Verein beitreten", "Mitglied in einem Verein werden"],
        ["der Vereinsgeist", "das Gefühl von Zusammenhalt in einem Verein"],
        ["das Engagement", "freiwilliger und aktiver Einsatz für eine Sache"],
        ["jemanden von etwas überzeugen", "eine Person durch Gründe zu einer Meinung bringen"],
        ["das Zusammengehörigkeitsgefühl", "das Gefühl, Teil einer Gemeinschaft zu sein"],
        ["die Vereinsarbeit", "alle organisatorischen und praktischen Tätigkeiten im Verein"],
        ["die Mitgliedschaft", "der Status als Mitglied einer Organisation"],
      ],
      ["Für … spricht, dass … / Dagegen spricht …", "Im Gegensatz zu …"],
      "Wirb in neunzig Sekunden für einen Verein und reagiere auf einen Einwand.",
      "Formuliere fünf überzeugende Argumente für freiwilliges Engagement.",
    ),
    profile(
      [
        "Ich diskutiere die Wirkung digitaler Medien auf Aufmerksamkeit und Erholung.",
        "Ich unterscheide normale Nutzung von übermäßigem Verhalten.",
        "Ich verwende trennbare und untrennbare Verben sicher.",
      ],
      [
        ["die Aufmerksamkeit", "die bewusste Konzentration auf etwas"],
        ["das Nutzungsverhalten", "die Art, wie jemand ein Medium verwendet"],
        ["die Handysucht", "eine starke Abhängigkeit von der Smartphone-Nutzung"],
        ["die Ruhepause", "eine kurze Phase ohne Belastung"],
        ["einer Versuchung widerstehen", "einen starken Wunsch bewusst nicht erfüllen"],
        ["die Erholungsphase", "ein Zeitraum zur körperlichen oder geistigen Regeneration"],
        ["exzessiv", "übermäßig und kaum kontrolliert"],
        ["die Langzeitfolge", "eine Wirkung, die erst spät oder dauerhaft sichtbar wird"],
      ],
      ["trennbar: übergehen / untrennbar: überdenken", "zu etwas führen / zwischen zwei Dingen unterscheiden"],
      "Berichte über einen Tag mit bewusst reduzierter Smartphone-Nutzung.",
      "Entwirf einen Digital-Detox-Plan mit fünf konkreten Regeln.",
    ),
    profile(
      [
        "Ich löse Konflikte in einer Wohngemeinschaft sachlich.",
        "Ich widerspreche höflich und handle Vereinbarungen aus.",
        "Ich schreibe einen formellen Beschwerdebrief mit Forderung und Frist.",
      ],
      [
        ["der Putzplan", "eine feste Verteilung der Reinigungsaufgaben"],
        ["Rücksicht nehmen", "die Bedürfnisse anderer beachten"],
        ["eine Vereinbarung treffen", "gemeinsam eine verbindliche Regel festlegen"],
        ["einen Mangel beheben", "einen Fehler oder Schaden beseitigen"],
        ["die Beschwerde", "eine formelle Äußerung von Unzufriedenheit"],
        ["der Zoff", "ein heftiger, meist persönlicher Streit"],
        ["der Hauptmieter", "die Person mit dem Hauptmietvertrag"],
        ["die Hausverwaltung", "die Organisation, die ein Gebäude verwaltet"],
      ],
      ["Aus meiner Sicht … / Ich sehe das anders …", "Ich fordere Sie hiermit auf, den Mangel umgehend zu beheben."],
      "Führe eine kurze WG-Besprechung und vereinbare drei verbindliche Regeln.",
      "Schreibe einen Beschwerdebrief von 160 bis 180 Wörtern über einen Wohnungsmangel.",
    ),
    review(
      "Alltägliches",
      "Konnektoren sowie trennbare und untrennbare Verben",
      [
        ["das Zeitgefühl", "die subjektive Wahrnehmung von Zeit"],
        ["die Entschleunigung", "die bewusste Verringerung des Lebenstempos"],
        ["das Engagement", "freiwilliger und aktiver Einsatz für eine Sache"],
        ["das Zusammengehörigkeitsgefühl", "das Gefühl, Teil einer Gemeinschaft zu sein"],
        ["die Langzeitfolge", "eine Wirkung, die spät oder dauerhaft sichtbar wird"],
        ["einer Versuchung widerstehen", "einen starken Wunsch bewusst nicht erfüllen"],
        ["Rücksicht nehmen", "die Bedürfnisse anderer beachten"],
        ["einen Mangel beheben", "einen Fehler oder Schaden beseitigen"],
      ],
    ),
  ],
  [
    profile(
      [
        "Ich ordne Straftaten passenden juristischen Begriffen zu.",
        "Ich unterscheide zulässiges, rechtswidriges und strafbares Handeln.",
        "Ich beschreibe Tat, Absicht und mögliche Folge präzise.",
      ],
      [
        ["der Betrug", "eine Täuschung mit dem Ziel eines eigenen Vorteils"],
        ["der Diebstahl", "die rechtswidrige Wegnahme fremden Eigentums"],
        ["die Körperverletzung", "die körperliche Schädigung einer anderen Person"],
        ["die Straftat", "eine Handlung, die gegen ein Strafgesetz verstößt"],
        ["vorsätzlich", "bewusst und mit klarer Absicht"],
        ["die Erpressung", "eine Forderung, die mit einer Drohung verbunden ist"],
        ["die Sachbeschädigung", "die absichtliche Beschädigung fremden Eigentums"],
        ["die Urkundenfälschung", "das Herstellen oder Verändern eines falschen Dokuments"],
      ],
      ["sich strafbar machen", "eine Straftat begehen / unter Strafe stehen"],
      "Ordne mehrere Fälle juristisch ein und begründe deine Entscheidung.",
      "Schreibe acht kurze Fallbeschreibungen mit passenden Rechtsbegriffen.",
    ),
    profile(
      [
        "Ich berichte strukturiert über einen ungewöhnlichen Kriminalfall.",
        "Ich unterscheide Tat, Beute, Fahndung und Verhaftung.",
        "Ich verwende besondere Passivformen korrekt.",
      ],
      [
        ["die Fahndung", "die gezielte Suche der Polizei nach einer Person"],
        ["die Beute", "das bei einer Straftat erlangte Gut"],
        ["die Verhaftung", "die Festnahme einer verdächtigen Person"],
        ["die Zeugenaussage", "die Schilderung eines Ereignisses durch einen Zeugen"],
        ["ermitteln", "systematisch Informationen zu einer Straftat sammeln"],
        ["die Überwachungskamera", "eine Kamera zur Kontrolle eines Bereichs"],
        ["geistesgegenwärtig", "in einer Gefahrensituation schnell und richtig handelnd"],
        ["unauffällig", "ohne besondere Aufmerksamkeit zu erregen"],
      ],
      ["Der Täter wurde verhaftet.", "Der Tresor ließ sich nicht öffnen."],
      "Berichte als Nachrichtensprecher über einen ungewöhnlichen Kriminalfall.",
      "Schreibe einen Polizeibericht mit Tat, Ablauf, Beweisen und aktuellem Ermittlungsstand.",
    ),
    profile(
      [
        "Ich beschreibe Entwicklungen der Jugendkriminalität anhand von Daten.",
        "Ich fasse unterschiedliche Sichtweisen auf Strafe und Prävention zusammen.",
        "Ich begründe eine Maßnahme zur Vermeidung von Straftaten.",
      ],
      [
        ["die Jugendkriminalität", "Straftaten, die von Jugendlichen begangen werden"],
        ["der Rückgang", "eine Verringerung im Vergleich zu einem früheren Wert"],
        ["eine Strafe verhängen", "eine rechtliche Sanktion offiziell festsetzen"],
        ["die Vermeidung", "das bewusste Verhindern eines Ereignisses"],
        ["die Sichtweise", "eine bestimmte Perspektive auf ein Thema"],
        ["die Häufigkeit", "die Anzahl, wie oft etwas vorkommt"],
        ["der Strafrichter", "ein Richter, der über Straftaten entscheidet"],
        ["differenzieren", "wichtige Unterschiede genau berücksichtigen"],
      ],
      ["Die Grafik verzeichnet einen Rückgang um …", "Aus Sicht der Prävention wäre …"],
      "Diskutiere mit mir, ob strengere Strafen Jugendkriminalität wirksam verringern.",
      "Schreibe eine strukturierte Auswertung einer Grafik zur Jugendkriminalität.",
    ),
    profile(
      [
        "Ich verstehe Texte über ungewöhnliche Gesetze.",
        "Ich erläutere den Weg von einem Entwurf zum Gesetz.",
        "Ich verwende modale Partizipialkonstruktionen.",
      ],
      [
        ["die Gesetzgebung", "der gesamte Prozess des Erlassens von Gesetzen"],
        ["die Gesetzeslücke", "ein nicht geregelter Bereich im bestehenden Recht"],
        ["ein Gesetz erlassen", "eine Regelung offiziell als Gesetz beschließen"],
        ["der Entwurf", "eine noch nicht endgültige Fassung eines Textes"],
        ["befürworten", "eine Idee oder einen Vorschlag unterstützen"],
        ["der Gesetzgeber", "die staatliche Instanz, die Gesetze beschließt"],
        ["das Gremium", "eine Gruppe mit einer gemeinsamen Entscheidungsaufgabe"],
        ["die Rechtsprechung", "die Entscheidungen und Auslegung der Gerichte"],
      ],
      ["die zu beachtende Regel", "ein noch zu verabschiedendes Gesetz"],
      "Präsentiere ein ungewöhnliches Gesetz und beurteile seinen Zweck.",
      "Formuliere einen kurzen Gesetzesentwurf mit Problem, Regel und Begründung.",
    ),
    profile(
      [
        "Ich fasse Handlung und Figuren eines Krimis zusammen.",
        "Ich diskutiere Wirkung und Beliebtheit von Kriminalliteratur.",
        "Ich handle in einer Gruppe eine begründete Auswahl aus.",
      ],
      [
        ["der Ermittler", "eine Person, die einen Kriminalfall untersucht"],
        ["die Krimihandlung", "die Abfolge der Ereignisse in einem Kriminalwerk"],
        ["der Nervenkitzel", "angenehme Spannung in einer gefährlich wirkenden Situation"],
        ["die Spur", "ein Hinweis, der bei der Aufklärung helfen kann"],
        ["das Verhör", "eine intensive Befragung durch Ermittlungsbehörden"],
        ["die Auflösung", "die Erklärung des Falls am Ende eines Krimis"],
        ["die Bedrohung", "eine mögliche oder angekündigte Gefahr"],
        ["der oder die Schuldige", "die Person, die für eine Tat verantwortlich ist"],
      ],
      ["Die Handlung setzt damit ein, dass …", "Für diese Auswahl spricht vor allem …"],
      "Fasse einen Krimi zusammen, ohne seine Auflösung sofort zu verraten.",
      "Schreibe eine kurze Rezension mit Handlung, Wirkung und begründetem Urteil.",
    ),
    review(
      "Recht so!",
      "Passivformen und modale Partizipialkonstruktionen",
      [
        ["die Straftat", "eine Handlung, die gegen ein Strafgesetz verstößt"],
        ["vorsätzlich", "bewusst und mit klarer Absicht"],
        ["die Fahndung", "die gezielte Suche der Polizei nach einer Person"],
        ["die Zeugenaussage", "die Schilderung eines Ereignisses durch einen Zeugen"],
        ["die Jugendkriminalität", "Straftaten, die von Jugendlichen begangen werden"],
        ["differenzieren", "wichtige Unterschiede genau berücksichtigen"],
        ["die Gesetzeslücke", "ein nicht geregelter Bereich im bestehenden Recht"],
        ["der Nervenkitzel", "angenehme Spannung bei einer gefährlich wirkenden Situation"],
      ],
    ),
  ],
  [
    profile(
      [
        "Ich beschreibe, wie Emotionen sprachlich und bildlich dargestellt werden.",
        "Ich drücke Mitgefühl, Ermutigung und Begeisterung differenziert aus.",
        "Ich deute die Stimmung eines kurzen Textes.",
      ],
      [
        ["mitfühlen", "die Gefühle einer anderen Person innerlich teilen"],
        ["jemandem Mut machen", "eine Person ermuntern und stärken"],
        ["unbeschwert", "frei von Sorgen und innerer Belastung"],
        ["für etwas schwärmen", "mit großer Begeisterung über etwas sprechen"],
        ["vergebens", "ohne den gewünschten Erfolg"],
        ["ungetrübt", "nicht durch etwas Negatives beeinträchtigt"],
        ["das Geleit", "Begleitung und Schutz auf einem Weg"],
        ["jemandem einen Fehler vergeben", "einer Person einen Fehler nicht länger vorwerfen"],
      ],
      ["Die Stimmung wirkt auf mich …, weil …", "Ich kann gut mitfühlen, wenn …"],
      "Beschreibe eine emotionale Szene und erkläre ihre Wirkung.",
      "Schreibe einen kurzen Text, der Ermutigung und Mitgefühl ausdrückt.",
    ),
    profile(
      [
        "Ich verstehe Aufbau und Aussage alltagsnaher Experimente.",
        "Ich unterscheide Beobachtung, Deutung und Behauptung.",
        "Ich verwende subjektive Modalverben zur Distanzierung.",
      ],
      [
        ["die Alltagsforschung", "Forschung zu gewöhnlichen Situationen des täglichen Lebens"],
        ["der Gesamteindruck", "die zusammenfassende Wirkung aller Einzelheiten"],
        ["die Resonanz", "die Reaktion, die eine Handlung oder Aussage auslöst"],
        ["untermauern", "eine Aussage mit Belegen überzeugender machen"],
        ["subjektiv", "von persönlichen Gefühlen und Urteilen beeinflusst"],
        ["der Hirnscan", "eine bildliche Untersuchung der Gehirnaktivität"],
        ["der Forschungsauftrag", "eine klar festgelegte Aufgabe für eine Untersuchung"],
        ["einer Frage nachgehen", "eine Frage systematisch untersuchen"],
      ],
      ["Die Untersuchung soll gezeigt haben, dass …", "Das Ergebnis dürfte bedeuten, dass …"],
      "Erkläre ein Alltagsexperiment und trenne Ergebnis von Interpretation.",
      "Schreibe eine kritische Zusammenfassung eines behaupteten Forschungsergebnisses.",
    ),
    profile(
      [
        "Ich diskutiere biologische und gesellschaftliche Erklärungen für Verhalten.",
        "Ich erkenne und hinterfrage Rollenbilder und Klischees.",
        "Ich schreibe einen ausgewogenen Forumsbeitrag.",
      ],
      [
        ["die Veranlagung", "eine angeborene Neigung oder Fähigkeit"],
        ["das Rollenbild", "eine gesellschaftliche Vorstellung über erwartetes Verhalten"],
        ["der Verhaltensunterschied", "eine Abweichung in der Art zu handeln"],
        ["das Klischee", "eine stark vereinfachte und oft starre Vorstellung"],
        ["die Übereinstimmung", "das Vorhandensein gleicher oder ähnlicher Merkmale"],
        ["das Chromosom", "ein Träger genetischer Informationen in einer Zelle"],
        ["die Neigung", "eine erkennbare Tendenz oder Vorliebe"],
        ["jemandem etwas weismachen", "eine Person von etwas Zweifelhaftem überzeugen wollen"],
      ],
      ["Einer biologischen Erklärung steht entgegen, dass …", "Ein solches Rollenbild greift zu kurz, weil …"],
      "Diskutiere mit mir eine verbreitete Behauptung über Verhaltensunterschiede.",
      "Schreibe einen Forumsbeitrag, der ein Klischee differenziert prüft.",
    ),
    profile(
      [
        "Ich verstehe Texte und Aussagen über Hochbegabung.",
        "Ich drücke unterschiedliche Grade von Sicherheit aus.",
        "Ich unterscheide Anzeichen, Vermutung und Diagnose.",
      ],
      [
        ["die Hochbegabung", "eine außergewöhnlich hohe intellektuelle Fähigkeit"],
        ["das Anzeichen", "ein Hinweis auf einen möglichen Zustand"],
        ["auf etwas hindeuten", "ein mögliches Ergebnis erkennen lassen"],
        ["der Grad der Sicherheit", "das Maß, wie sicher eine Aussage ist"],
        ["sich hervortun", "durch besondere Leistungen auffallen"],
        ["denkbar", "als Möglichkeit vorstellbar"],
        ["zweifellos", "ohne vernünftigen Zweifel"],
        ["die Beratungsstelle", "eine Einrichtung, die fachliche Beratung anbietet"],
      ],
      ["Es ist denkbar oder möglich, dass …", "Das lässt darauf schließen, dass …"],
      "Ordne mehrere Aussagen nach ihrem Grad der Sicherheit und begründe die Reihenfolge.",
      "Schreibe eine vorsichtige Einschätzung, die Anzeichen klar von Diagnose trennt.",
    ),
    profile(
      [
        "Ich diskutiere Kindheit, Erziehung und Leistungsdruck.",
        "Ich vergleiche unterschiedliche pädagogische Positionen.",
        "Ich argumentiere differenziert und reagiere auf Einwände.",
      ],
      [
        ["der Leistungsdruck", "die Belastung durch hohe Erwartungen an Leistung"],
        ["der Freiraum", "ein Bereich für selbstständige Entscheidungen und Entwicklung"],
        ["die Individualität", "die besondere und unverwechselbare Eigenart einer Person"],
        ["durchhalten", "trotz Schwierigkeiten bis zum Ende weitermachen"],
        ["das Selbstbewusstsein", "Vertrauen in die eigenen Fähigkeiten und den eigenen Wert"],
        ["die Leistungserwartung", "eine Vorstellung davon, welche Leistung erreicht werden soll"],
        ["das Dilemma", "eine schwierige Wahl zwischen problematischen Möglichkeiten"],
        ["die Hingabe", "starker und dauerhafter Einsatz für eine Sache"],
      ],
      ["Einerseits brauchen Kinder …, andererseits …", "Über den Tellerrand geblickt …"],
      "Diskutiere mit mir, wie viel Leistungsdruck und Freiraum Kinder benötigen.",
      "Schreibe einen argumentativen Text über eine prägende Kindheitserfahrung.",
    ),
    review(
      "Du bist, was du bist",
      "subjektive Modalverben und sprachliche Vermutungen",
      [
        ["mitfühlen", "die Gefühle einer anderen Person innerlich teilen"],
        ["unbeschwert", "frei von Sorgen und innerer Belastung"],
        ["die Alltagsforschung", "Forschung zu gewöhnlichen Situationen"],
        ["untermauern", "eine Aussage mit Belegen überzeugender machen"],
        ["die Veranlagung", "eine angeborene Neigung oder Fähigkeit"],
        ["das Klischee", "eine stark vereinfachte und starre Vorstellung"],
        ["auf etwas hindeuten", "ein mögliches Ergebnis erkennen lassen"],
        ["der Freiraum", "ein Bereich für selbstständige Entwicklung"],
      ],
    ),
  ],
  [
    profile(
      [
        "Ich benenne verschiedene Kunstformen und Materialien.",
        "Ich beschreibe meine persönliche Beziehung zu Kunst.",
        "Ich begründe, was ich als Kunst wahrnehme.",
      ],
      [
        ["das Porzellan", "ein feines, hartes Material für Geschirr und Kunstobjekte"],
        ["das Kunsthandwerk", "die handwerkliche Herstellung künstlerischer Gegenstände"],
        ["das Tattoo", "ein dauerhaft in die Haut eingebrachtes Motiv"],
      ],
      ["Für mich zählt … zur Kunst, weil …", "Die handwerkliche Ausführung wirkt …"],
      "Präsentiere ein Kunstobjekt und erkläre seine Wirkung auf dich.",
      "Schreibe eine kurze persönliche Definition von Kunst mit zwei Beispielen.",
    ),
    profile(
      [
        "Ich verstehe und bewerte Methoden zur Ideenfindung.",
        "Ich erkläre Bedingungen, die Kreativität fördern oder hemmen.",
        "Ich forme Präpositionalergänzungen sprachlich um.",
      ],
      [
        ["einfallsreich", "voller neuer und ungewöhnlicher Ideen"],
        ["der Ideenreichtum", "eine große Vielfalt kreativer Einfälle"],
        ["das Brainstorming", "eine Methode zum ungefilterten Sammeln von Ideen"],
        ["die Kreativtechnik", "ein planvolles Verfahren zur Entwicklung neuer Ideen"],
        ["widerlegen", "zeigen, dass eine Behauptung falsch ist"],
        ["altbewährt", "seit langer Zeit erfolgreich verwendet"],
        ["der Konkurrenzdruck", "die Belastung durch starke Mitbewerber"],
        ["neue Wege betreten", "ungewohnte Lösungen oder Methoden ausprobieren"],
      ],
      ["Der Erfolg basiert auf … ↔ Der Erfolg beruht darauf, dass …", "Im Rückgriff auf …"],
      "Führe eine kurze Kreativtechnik durch und bewerte ihr Ergebnis.",
      "Schreibe eine Anleitung für eine Methode zur Ideenfindung.",
    ),
    profile(
      [
        "Ich fasse die Handlung eines Films knapp zusammen.",
        "Ich vergleiche Buchvorlage und Verfilmung.",
        "Ich beschreibe eine Grafik zum Sehverhalten.",
      ],
      [
        ["die Buchverfilmung", "ein Film, der auf einem Buch basiert"],
        ["die Hauptrolle", "die wichtigste Figur oder Aufgabe in einem Film"],
        ["verkörpern", "eine Figur überzeugend darstellen"],
        ["das Sehverhalten", "die Art und Häufigkeit des Konsums visueller Medien"],
        ["die Ähnlichkeit", "eine erkennbare Übereinstimmung von Merkmalen"],
        ["über etwas hinauswachsen", "sich über eine frühere Grenze hinaus entwickeln"],
        ["jemanden ansprechen", "Interesse oder eine positive Reaktion bei jemandem auslösen"],
        ["auf etwas verweisen", "auf eine Information oder Quelle aufmerksam machen"],
      ],
      ["Der Film handelt von …, ohne dass …", "Im Unterschied zur Vorlage …"],
      "Fasse einen Film in neunzig Sekunden zusammen und vergleiche ihn mit seiner Vorlage.",
      "Schreibe eine Grafikbeschreibung zum Sehverhalten mit vorsichtiger Interpretation.",
    ),
    profile(
      [
        "Ich verstehe Chancen und Belastungen eines Künstlerlebens.",
        "Ich kommentiere Ratschläge und berufliche Entscheidungen.",
        "Ich verknüpfe Argumente mit passenden Konnektoren.",
      ],
      [
        ["die Aufnahmeprüfung", "eine Prüfung vor der Aufnahme in eine Bildungseinrichtung"],
        ["das Durchhaltevermögen", "die Fähigkeit, trotz Schwierigkeiten weiterzumachen"],
        ["die Kunstwelt", "alle Personen und Institutionen im Bereich der Kunst"],
        ["das Standbein", "eine verlässliche berufliche oder finanzielle Grundlage"],
        ["die Leidenschaft", "eine starke und dauerhafte Begeisterung"],
        ["der Künstleralltag", "das gewöhnliche Arbeitsleben einer künstlerisch tätigen Person"],
        ["sich der Kunst verschreiben", "das eigene Leben konsequent der Kunst widmen"],
        ["ausfeilen", "etwas in vielen Einzelheiten verbessern"],
      ],
      ["Demgegenüber ist zu bedenken, dass …", "Vielmehr kommt es darauf an, …"],
      "Berate eine Person, die eine künstlerische Laufbahn beginnen möchte.",
      "Schreibe einen Kommentar zu Chancen und Risiken eines Lebens für die Kunst.",
    ),
    profile(
      [
        "Ich verstehe autobiografische Texte über das Lesen.",
        "Ich diskutiere literarische Vorlieben präzise.",
        "Ich verfasse eine begründete Buchbesprechung.",
      ],
      [
        ["die Leseratte", "eine Person, die sehr viel und gern liest"],
        ["die Buchkritik", "eine fachliche Bewertung eines Buches"],
        ["lesenswert", "so gut oder interessant, dass sich das Lesen lohnt"],
        ["tiefsinnig", "geistig anspruchsvoll und von tiefer Bedeutung"],
        ["die Buchbesprechung", "eine zusammenfassende und wertende Darstellung eines Buches"],
        ["anregend", "zu neuen Gedanken oder Gesprächen motivierend"],
        ["kurzweilig", "unterhaltsam und ohne langweilig zu wirken"],
        ["die Inspiration", "ein Impuls für neue Gedanken oder kreative Arbeit"],
      ],
      ["Besonders lesenswert ist das Buch, weil …", "Die Handlung ist zwar …, dennoch …"],
      "Stelle ein Buch vor und beantworte kritische Rückfragen dazu.",
      "Schreibe eine Buchbesprechung mit Inhalt, Wirkung und Gesamturteil.",
    ),
    review(
      "Die schöne Welt der Künste",
      "Präpositionalergänzungen und argumentierende Konnektoren",
      [
        ["das Kunsthandwerk", "die handwerkliche Herstellung künstlerischer Gegenstände"],
        ["der Ideenreichtum", "eine große Vielfalt kreativer Einfälle"],
        ["neue Wege betreten", "ungewohnte Lösungen ausprobieren"],
        ["die Buchverfilmung", "ein Film, der auf einem Buch basiert"],
        ["verkörpern", "eine Figur überzeugend darstellen"],
        ["das Durchhaltevermögen", "die Fähigkeit, trotz Schwierigkeiten weiterzumachen"],
        ["das Standbein", "eine verlässliche berufliche oder finanzielle Grundlage"],
        ["tiefsinnig", "geistig anspruchsvoll und von tiefer Bedeutung"],
      ],
    ),
  ],
  [
    profile(
      [
        "Ich ordne technische und persönliche Ereignisse zeitlich ein.",
        "Ich beschreibe überraschende Entwicklungen präzise.",
        "Ich begründe, warum eine Innovation bedeutsam ist.",
      ],
      [
        ["eintreffen", "an einem Ort ankommen oder wie erwartet geschehen"],
        ["revolutionieren", "einen Bereich grundlegend und dauerhaft verändern"],
        ["in den Startlöchern stehen", "vollständig bereit für den Beginn sein"],
        ["erschwinglich", "preislich für viele Menschen bezahlbar"],
        ["der Wahnsinn", "etwas außergewöhnlich Intensives oder kaum Fassbares"],
        ["der Marsrover", "ein ferngesteuertes Forschungsfahrzeug auf dem Mars"],
        ["das Funksignal", "eine drahtlos übertragene technische Information"],
        ["das Gefährt", "ein Fahrzeug, besonders ein ungewöhnliches"],
      ],
      ["Damals war noch nicht abzusehen, dass …", "Diese Entwicklung revolutionierte …"],
      "Ordne mehrere Innovationen zeitlich ein und wähle die folgenreichste aus.",
      "Schreibe einen kurzen Zeitstrahl mit acht Ereignissen und präzisen Zeitangaben.",
    ),
    profile(
      [
        "Ich erkläre zentrale Gedächtnissysteme und ihre Funktionen.",
        "Ich spreche über Strategien des Erinnerns und Vergessens.",
        "Ich beherrsche Besonderheiten von Konditionalsätzen.",
      ],
      [
        ["das Kurzzeitgedächtnis", "der Speicher für kurzfristig verfügbare Informationen"],
        ["das Langzeitgedächtnis", "der Speicher für länger erhaltene Informationen"],
        ["die Gedächtnislücke", "eine fehlende Erinnerung an einen Zeitraum oder Inhalt"],
        ["die Speicherung", "das dauerhafte Aufbewahren von Informationen"],
        ["abrufen", "eine gespeicherte Information wieder verfügbar machen"],
        ["die Gedächtnisstütze", "ein Hilfsmittel, das das Erinnern erleichtert"],
        ["das Faktenwissen", "Kenntnisse über Daten, Begriffe und Sachverhalte"],
        ["das Neuron", "eine Nervenzelle, die Informationen verarbeitet"],
      ],
      ["Hätte ich mir das notiert, …", "Sollte die Erinnerung fehlen, …"],
      "Erkläre eine wirksame Gedächtnisstrategie und wende sie auf ein Beispiel an.",
      "Führe ein kurzes Experiment zum Erinnern durch und protokolliere das Ergebnis.",
    ),
    profile(
      [
        "Ich verstehe, wie falsche Erinnerungen entstehen können.",
        "Ich unterscheide Rekonstruktion, Auswahl und Manipulation.",
        "Ich schreibe einen differenzierten Forumsbeitrag.",
      ],
      [
        ["die Rekonstruktion", "die nachträgliche Wiederherstellung aus einzelnen Informationen"],
        ["die Manipulation", "die gezielte, oft verdeckte Beeinflussung"],
        ["selektiv", "nur bestimmte Teile auswählend"],
        ["die Wissenslücke", "ein fehlender Teil des eigenen Wissens"],
        ["der Zeitzeuge", "eine Person, die ein historisches Ereignis selbst erlebt hat"],
        ["die Fälschung", "eine absichtlich hergestellte unechte Darstellung"],
        ["filtern", "bestimmte Informationen auswählen und andere ausschließen"],
        ["vermischen", "verschiedene Inhalte so verbinden, dass Grenzen unscharf werden"],
      ],
      ["Erinnerungen werden rekonstruiert, indem …", "Es lässt sich nicht ausschließen, dass …"],
      "Diskutiere mit mir, wie zuverlässig persönliche Erinnerungen sein können.",
      "Schreibe einen Forumsbeitrag zu einer Sendung über falsche Erinnerungen.",
    ),
    profile(
      [
        "Ich verstehe Ursachen und Alltagserfahrungen bei Gesichtsblindheit.",
        "Ich erkläre Verwechslungen und soziale Folgen.",
        "Ich verwende Modalitätsverben präzise.",
      ],
      [
        ["die Prosopagnosie", "eine Störung beim Erkennen vertrauter Gesichter"],
        ["die Verwechslung", "die falsche Identifizierung von Personen oder Dingen"],
        ["angeboren", "seit der Geburt vorhanden"],
        ["das Störungsbild", "die Gesamtheit typischer Merkmale einer Störung"],
        ["sich schwertun", "bei einer Aufgabe große Schwierigkeiten haben"],
        ["der Prosopagnostiker", "eine Person mit Schwierigkeiten beim Erkennen von Gesichtern"],
        ["die Ausgrenzung", "der Ausschluss einer Person aus einer Gemeinschaft"],
        ["gegensteuern", "bewusst Maßnahmen gegen eine negative Entwicklung ergreifen"],
      ],
      ["Das Problem scheint angeboren zu sein.", "Die Betroffenen vermögen Gesichter nicht sicher zuzuordnen."],
      "Erkläre Gesichtsblindheit und reagiere auf zwei typische Missverständnisse.",
      "Schreibe eine verständliche Information für das Umfeld einer betroffenen Person.",
    ),
    profile(
      [
        "Ich erschließe einen literarischen Text über Erinnerungen.",
        "Ich spreche differenziert über Trauer, Schuld und Reue.",
        "Ich verfasse einen persönlichen, aber klar strukturierten Erinnerungstext.",
      ],
      [
        ["die Kindheitserinnerung", "eine Erinnerung an ein Erlebnis aus der Kindheit"],
        ["die Trauer", "tiefer Schmerz nach einem Verlust"],
        ["das Schuldgefühl", "das belastende Gefühl, etwas Falsches getan zu haben"],
        ["literarisch", "zur Literatur gehörend oder künstlerisch gestaltet"],
        ["die Reue", "Bedauern über eine eigene frühere Handlung"],
        ["die Familiengeschichte", "die überlieferte Vergangenheit einer Familie"],
        ["die Erleichterung", "das Gefühl, von einer Belastung befreit zu sein"],
        ["die Sprachlosigkeit", "die Unfähigkeit, Gefühle oder Gedanken in Worte zu fassen"],
      ],
      ["Rückblickend wird mir bewusst, dass …", "Was mir besonders in Erinnerung geblieben ist, …"],
      "Erzähle eine prägende Erinnerung und reflektiere ihre heutige Bedeutung.",
      "Schreibe einen literarisch gestalteten Erinnerungstext von etwa 180 Wörtern.",
    ),
    review(
      "Erinnerungen",
      "Konditionalsätze und Modalitätsverben",
      [
        ["revolutionieren", "einen Bereich grundlegend und dauerhaft verändern"],
        ["in den Startlöchern stehen", "vollständig bereit für den Beginn sein"],
        ["die Gedächtnislücke", "eine fehlende Erinnerung an einen Zeitraum oder Inhalt"],
        ["abrufen", "eine gespeicherte Information wieder verfügbar machen"],
        ["die Rekonstruktion", "die nachträgliche Wiederherstellung aus einzelnen Informationen"],
        ["selektiv", "nur bestimmte Teile auswählend"],
        ["die Prosopagnosie", "eine Störung beim Erkennen vertrauter Gesichter"],
        ["die Sprachlosigkeit", "die Unfähigkeit, Gefühle oder Gedanken in Worte zu fassen"],
      ],
    ),
  ],
];

const chapterGroupB = [
  [
    profile(
      [
        "Ich verstehe grundlegende wirtschaftliche Kennzahlen und Entwicklungen.",
        "Ich beschreibe steigende und fallende Tendenzen präzise.",
        "Ich erkläre die Folgen einer wirtschaftlichen Veränderung.",
      ],
      [
        ["der Abschwung", "eine Phase sinkender wirtschaftlicher Aktivität"],
        ["die Konjunktur", "die aktuelle Lage und Entwicklung einer Volkswirtschaft"],
        ["der Aktienkurs", "der aktuelle Preis einer Aktie"],
        ["das Wirtschaftswachstum", "die Zunahme der gesamtwirtschaftlichen Leistung"],
        ["zahlungsunfähig", "nicht mehr in der Lage, Rechnungen zu bezahlen"],
        ["die Börse", "ein organisierter Markt für Wertpapiere"],
        ["der Umsatz", "der gesamte Erlös eines Unternehmens in einem Zeitraum"],
        ["die Marktlücke", "ein noch nicht ausreichend gedeckter Bedarf am Markt"],
      ],
      ["Der Wert steigt oder sinkt um …", "Das wirkt sich auf … aus."],
      "Präsentiere eine kurze Wirtschaftsnachricht mit mindestens drei Kennzahlen.",
      "Formuliere acht präzise Sätze zu wirtschaftlichem Aufschwung und Abschwung.",
    ),
    profile(
      [
        "Ich erkläre den Strukturwandel einer Industrieregion.",
        "Ich ordne Entwicklungsphasen chronologisch.",
        "Ich forme Temporalsätze in Präpositionalangaben um und zurück.",
      ],
      [
        ["das Ballungsgebiet", "ein dicht besiedelter Raum mit mehreren Städten"],
        ["der Bergbau", "die Gewinnung von Rohstoffen aus der Erde"],
        ["die Kohlekrise", "der wirtschaftliche Niedergang des Kohlebergbaus"],
        ["der Wiederaufbau", "der erneute Aufbau nach einer Zerstörung"],
        ["die Verkehrsanbindung", "die Erreichbarkeit eines Ortes mit Verkehrsmitteln"],
        ["der Dienstleistungssektor", "der Wirtschaftsbereich, der Dienstleistungen anbietet"],
        ["die Entwicklungsphase", "ein zeitlich begrenzter Abschnitt einer Veränderung"],
        ["die Rohstoffverarbeitung", "die Bearbeitung natürlicher Ausgangsstoffe"],
      ],
      ["nachdem … ↔ nach dem …", "während … ↔ während des …"],
      "Stelle den Wandel einer Stadt oder Region in drei Phasen vor.",
      "Schreibe etwa 150 Wörter und verwende bevor, nachdem, während und seitdem.",
    ),
    profile(
      [
        "Ich diskutiere Gewissensfragen und unterscheide Recht von Moral.",
        "Ich bewerte Handlungen differenziert statt nur absolut.",
        "Ich drücke Zustimmung und Ablehnung respektvoll aus.",
      ],
      [
        ["die Gewissensbisse", "unangenehme Schuldgefühle nach einer Entscheidung"],
        ["bedenklich", "problematisch und Anlass zu ernsthafter Sorge"],
        ["die Moral", "Vorstellungen darüber, was richtig oder falsch ist"],
        ["vertretbar", "mit guten Gründen zu rechtfertigen"],
        ["missbilligen", "deutlich zeigen, dass man etwas nicht akzeptiert"],
        ["die Gewissensfrage", "eine Entscheidung, die moralische Zweifel auslöst"],
        ["der Sachverhalt", "alle relevanten Tatsachen eines Falls"],
        ["die Verpflichtung", "eine verbindliche Pflicht zu einem bestimmten Handeln"],
      ],
      ["Ich halte das für moralisch vertretbar, weil …", "Zwar …, dennoch …"],
      "Entscheide eine Gewissensfrage und begründe Prinzip, Ausnahme und Folge.",
      "Schreibe etwa 140 Wörter zu einer legalen, aber moralisch fragwürdigen Handlung.",
    ),
    profile(
      [
        "Ich verstehe Ursachen und Folgen der Globalisierung.",
        "Ich erkläre Produktionsverlagerung und internationalen Wettbewerb.",
        "Ich forme Kausal- und Modalsätze in präpositionale Ausdrücke um.",
      ],
      [
        ["der Absatzmarkt", "ein Markt, auf dem Produkte verkauft werden können"],
        ["die Produktionsstätte", "ein Ort, an dem Waren hergestellt werden"],
        ["der Wettbewerbsdruck", "der Zwang, sich gegen Konkurrenz zu behaupten"],
        ["die Verlagerung", "die Übertragung einer Tätigkeit an einen anderen Ort"],
        ["der Welthandel", "der internationale Austausch von Waren und Dienstleistungen"],
        ["der Strukturwandel", "eine grundlegende Veränderung wirtschaftlicher Strukturen"],
        ["der Preisdruck", "der Zwang, Preise wegen der Konkurrenz zu senken"],
        ["die Vernetzung", "die enge Verbindung von Personen, Firmen oder Systemen"],
      ],
      ["weil oder da … ↔ aufgrund des …", "indem oder dadurch, dass … ↔ durch …"],
      "Erkläre den Weg eines Produkts vom Produktionsort bis zum Verbraucher.",
      "Schreibe etwa 160 Wörter über Gewinner und Verlierer der Globalisierung.",
    ),
    profile(
      [
        "Ich verstehe Crowdfunding und weitere Finanzierungsformen.",
        "Ich präsentiere Nutzen, Zielgruppe und Besonderheit einer Projektidee.",
        "Ich führe ein Bankgespräch und verteidige einen Finanzierungsplan.",
      ],
      [
        ["das Crowdfunding", "die Finanzierung durch viele einzelne Unterstützende"],
        ["das Fremdkapital", "geliehenes Kapital, das zurückgezahlt werden muss"],
        ["der Businessplan", "ein schriftliches Konzept für ein Unternehmen"],
        ["die Kreditwürdigkeit", "die erwartete Fähigkeit, einen Kredit zurückzuzahlen"],
        ["das Alleinstellungsmerkmal", "eine Eigenschaft, die ein Angebot einzigartig macht"],
        ["die Gewinnbeteiligung", "ein vereinbarter Anteil am erzielten Gewinn"],
        ["die Zielgruppe", "die Personengruppe, für die ein Angebot gedacht ist"],
        ["das Vorhaben", "ein geplantes Projekt oder eine beabsichtigte Handlung"],
      ],
      ["Unser Vorhaben richtet sich an …", "Die Finanzierung setzt sich aus … zusammen."],
      "Präsentiere eine Projektidee mit Problem, Lösung, Zielgruppe und Finanzierung.",
      "Erstelle einen Kurz-Businessplan mit Idee, Kosten, Nutzen und Risiko.",
    ),
    review(
      "Wirtschaftsgipfel",
      "Temporal-, Kausal- und Modalsätze",
      [
        ["die Konjunktur", "die aktuelle Lage und Entwicklung einer Volkswirtschaft"],
        ["die Marktlücke", "ein noch nicht ausreichend gedeckter Bedarf am Markt"],
        ["der Strukturwandel", "eine grundlegende Veränderung wirtschaftlicher Strukturen"],
        ["die Verkehrsanbindung", "die Erreichbarkeit eines Ortes mit Verkehrsmitteln"],
        ["die Gewissensfrage", "eine Entscheidung, die moralische Zweifel auslöst"],
        ["vertretbar", "mit guten Gründen zu rechtfertigen"],
        ["der Wettbewerbsdruck", "der Zwang, sich gegen Konkurrenz zu behaupten"],
        ["das Alleinstellungsmerkmal", "eine Eigenschaft, die ein Angebot einzigartig macht"],
      ],
    ),
  ],
  [
    profile(
      [
        "Ich formuliere persönliche und berufliche Ziele präzise.",
        "Ich ordne Ziele nach Priorität und Zeithorizont.",
        "Ich benenne Motivation, Hindernis und nächsten Schritt.",
      ],
      [
        ["das Ziel aus den Augen verlieren", "ein wichtiges Vorhaben nicht mehr konsequent verfolgen"],
        ["der nächste Schritt", "die unmittelbar folgende Handlung in einem Plan"],
        ["unerreichbar", "auch mit großer Anstrengung nicht zu schaffen"],
        ["unbezahlbar", "so wertvoll, dass kein Preis angemessen wäre"],
        ["der Eintrag", "ein einzelner schriftlicher Beitrag oder Datensatz"],
        ["geschwind", "schnell und ohne lange Verzögerung"],
        ["herumirren", "ohne klare Orientierung umhergehen"],
        ["das Kalenderblatt", "eine einzelne Seite eines Kalenders"],
      ],
      ["Mein kurzfristiges oder langfristiges Ziel besteht darin, …", "Um dieses Ziel zu erreichen, werde ich …"],
      "Präsentiere drei Ziele in einer begründeten Reihenfolge.",
      "Schreibe einen Blogeintrag von etwa 120 Wörtern über ein Ziel und seinen ersten Schritt.",
    ),
    profile(
      [
        "Ich bewerte Nutzen und Risiken beruflicher Netzwerke.",
        "Ich argumentiere zu Datenschutz und digitaler Kommunikation.",
        "Ich bilde negative Konsekutivsätze korrekt.",
      ],
      [
        ["das Networking", "der gezielte Aufbau beruflicher Kontakte"],
        ["die Community", "eine Gruppe mit gemeinsamen Interessen"],
        ["die Datensicherheit", "der Schutz von Daten vor Verlust und Missbrauch"],
        ["die Cyberkriminalität", "Straftaten mithilfe digitaler Systeme"],
        ["der Standpunkt", "eine klar vertretene Meinung zu einer Frage"],
        ["der Austausch", "das gegenseitige Teilen von Informationen oder Erfahrungen"],
        ["der Betreiber", "die Person oder Firma, die eine Plattform führt"],
        ["die Kontaktaufnahme", "das Herstellen einer ersten Verbindung zu jemandem"],
      ],
      ["zu …, als dass …", "nicht genug …, um … zu …"],
      "Entwickle Regeln für ein sicheres und nützliches berufliches Netzwerk.",
      "Schreibe eine Stellungnahme von etwa 150 Wörtern zu beruflichem Networking.",
    ),
    profile(
      [
        "Ich führe eine Bestandsaufnahme meiner Ziele durch.",
        "Ich zerlege ein großes Ziel in realistische Teilaufgaben.",
        "Ich beschreibe Fortschritt und Hindernisse präzise.",
      ],
      [
        ["die Bestandsaufnahme", "eine systematische Erfassung des aktuellen Zustands"],
        ["der Leitfaden", "eine strukturierte Anleitung für ein Vorgehen"],
        ["die Haupttätigkeit", "die wichtigste regelmäßig ausgeübte Aufgabe"],
        ["planmäßig", "genau entsprechend dem vorher festgelegten Plan"],
        ["vorankommen", "Fortschritte in Richtung eines Ziels machen"],
        ["anfertigen", "etwas sorgfältig herstellen oder erstellen"],
        ["das Teilgebiet", "ein abgegrenzter Bereich eines größeren Themas"],
        ["systematisch", "nach einer klaren und geordneten Methode"],
      ],
      ["Zunächst nehme ich … in Angriff.", "Der Fortschritt zeigt sich daran, dass …"],
      "Erkläre deinen Weg zu einem Ziel anhand von drei messbaren Etappen.",
      "Erstelle einen Leitfaden mit Teilzielen, Terminen und Kontrollpunkten.",
    ),
    profile(
      [
        "Ich spreche differenziert über Vorsätze und Gewohnheiten.",
        "Ich analysiere Gründe für Aufschieben und Fehlschläge.",
        "Ich forme Konzessiv- und Finalsätze um.",
      ],
      [
        ["der Vorsatz", "eine feste Absicht, das eigene Verhalten zu ändern"],
        ["das Etappenziel", "ein Zwischenziel auf dem Weg zum Hauptziel"],
        ["der Fehlschlag", "ein Versuch, der nicht zum gewünschten Ergebnis führt"],
        ["aufschieben", "eine Aufgabe absichtlich auf später verschieben"],
        ["in die Tat umsetzen", "einen Plan tatsächlich verwirklichen"],
        ["die Anfangsbegeisterung", "starke Motivation zu Beginn eines Vorhabens"],
        ["die Verlockung", "ein starker Reiz, etwas Angenehmes zu tun"],
        ["straucheln", "vorübergehend scheitern oder den sicheren Weg verlieren"],
      ],
      ["obwohl … ↔ trotz …", "damit … ↔ zu dem Zweck, … zu …"],
      "Erkläre einen gescheiterten Vorsatz und entwickle einen besseren Neustart.",
      "Formuliere einen realistischen Vier-Wochen-Plan für einen persönlichen Vorsatz.",
    ),
    profile(
      [
        "Ich verstehe Formen und Motive ehrenamtlicher Arbeit.",
        "Ich fasse unterschiedliche Positionen zum Engagement zusammen.",
        "Ich schreibe einen gegliederten argumentativen Aufsatz.",
      ],
      [
        ["das Ehrenamt", "eine freiwillige Tätigkeit ohne reguläre Bezahlung"],
        ["das Gemeinwohl", "das Wohlergehen der gesamten Gesellschaft"],
        ["der Freiwilligendienst", "ein zeitlich begrenzter Dienst für die Gemeinschaft"],
        ["der Anreiz", "etwas, das Motivation für eine Handlung schafft"],
        ["das Gesamturteil", "eine abschließende Bewertung aller Gesichtspunkte"],
        ["die Geselligkeit", "das angenehme Zusammensein mit anderen"],
        ["der Mindestlohn", "die gesetzlich niedrigste erlaubte Bezahlung"],
        ["ausschlaggebend", "für eine Entscheidung besonders wichtig"],
      ],
      ["Für die Beurteilung ist ausschlaggebend, dass …", "Zusammenfassend überwiegt …"],
      "Fasse zwei Positionen zum Ehrenamt zusammen und beziehe begründet Stellung.",
      "Schreibe einen Aufsatz von etwa 180 Wörtern über Chancen und Grenzen des Ehrenamts.",
    ),
    review(
      "Ziele",
      "Konsekutiv-, Konzessiv- und Finalsätze",
      [
        ["das Ziel aus den Augen verlieren", "ein wichtiges Vorhaben nicht mehr konsequent verfolgen"],
        ["die Datensicherheit", "der Schutz von Daten vor Verlust und Missbrauch"],
        ["der Standpunkt", "eine klar vertretene Meinung zu einer Frage"],
        ["die Bestandsaufnahme", "eine systematische Erfassung des aktuellen Zustands"],
        ["das Etappenziel", "ein Zwischenziel auf dem Weg zum Hauptziel"],
        ["in die Tat umsetzen", "einen Plan tatsächlich verwirklichen"],
        ["das Gemeinwohl", "das Wohlergehen der gesamten Gesellschaft"],
        ["ausschlaggebend", "für eine Entscheidung besonders wichtig"],
      ],
    ),
  ],
  [
    profile(
      [
        "Ich spreche differenziert über Gesundheit und Fitness.",
        "Ich beschreibe Körperbewegungen und körperliches Befinden.",
        "Ich bewerte eigene Gesundheitsgewohnheiten realistisch.",
      ],
      [
        ["die Ausdauer", "die Fähigkeit, eine Belastung lange durchzuhalten"],
        ["der Ernährungsstil", "die typische Art, wie sich jemand ernährt"],
        ["der Gesundheitstest", "eine Untersuchung zur Einschätzung des Gesundheitszustands"],
        ["munter", "wach, lebendig und voller Energie"],
        ["jemandem guttun", "eine positive Wirkung auf eine Person haben"],
        ["die Fußsohle", "die Unterseite des Fußes"],
        ["das Fußgelenk", "das Gelenk zwischen Fuß und Unterschenkel"],
        ["sprinten", "eine kurze Strecke mit höchster Geschwindigkeit laufen"],
      ],
      ["Mir tut besonders gut, dass …", "Im Vergleich zu früher achte ich stärker auf …"],
      "Stelle deine Gesundheitsgewohnheiten vor und nenne eine realistische Verbesserung.",
      "Führe sieben Tage lang ein kurzes Gesundheitsprotokoll.",
    ),
    profile(
      [
        "Ich verstehe Wirkmechanismen und Grenzen von Placebos.",
        "Ich unterscheide Behauptung, Nachweis und Befürchtung.",
        "Ich verwende Infinitivsätze mit und ohne zu korrekt.",
      ],
      [
        ["das Placebo", "ein Präparat ohne spezifischen Wirkstoff"],
        ["die Nebenwirkung", "eine zusätzliche, oft unerwünschte Wirkung"],
        ["das Präparat", "ein hergestelltes medizinisches Mittel"],
        ["die Wirksamkeit", "das Ausmaß, in dem eine Behandlung wirkt"],
        ["die Befürchtung", "die Sorge, dass etwas Negatives eintreten könnte"],
        ["das Hausmittel", "eine traditionelle Behandlung mit einfachen Mitteln"],
        ["nachweisen", "mit Daten oder Belegen eindeutig zeigen"],
        ["die Aufklärung", "verständliche Information über Risiken und Möglichkeiten"],
      ],
      ["Der Patient hofft, schnell gesund zu werden.", "Es ist nachgewiesen, dass …"],
      "Erkläre den Placeboeffekt und trenne gesicherte Erkenntnisse von Vermutungen.",
      "Schreibe eine kurze Patienteninformation zu Wirkung und Nebenwirkung.",
    ),
    profile(
      [
        "Ich beschreibe Entwicklungen im Gesundheitswesen.",
        "Ich erkläre Prävention und wichtige Gesundheitsfaktoren.",
        "Ich vergleiche Daten und leite vorsichtige Schlüsse ab.",
      ],
      [
        ["die Lebenserwartung", "die durchschnittlich erwartete Lebensdauer"],
        ["die Krankheitsprävention", "Maßnahmen zur Verhinderung von Krankheiten"],
        ["das Gesundheitswesen", "alle Einrichtungen zur medizinischen Versorgung"],
        ["das Symptom", "ein wahrnehmbares Zeichen einer Krankheit"],
        ["zulasten", "mit einer negativen Wirkung für jemanden oder etwas"],
        ["das Gesundheitskonzept", "ein geplanter Ansatz zur Förderung von Gesundheit"],
        ["die Todesursache", "die Krankheit oder das Ereignis, das zum Tod führt"],
        ["das Präventionsangebot", "eine konkrete Maßnahme zur Vorbeugung"],
      ],
      ["Die Daten deuten darauf hin, dass …", "Diese Entwicklung geht zulasten von …"],
      "Vergleiche zwei Präventionsmaßnahmen und entscheide, welche wirksamer erscheint.",
      "Schreibe eine sachliche Auswertung einer selbst gewählten Gesundheitsgrafik.",
    ),
    profile(
      [
        "Ich bewerte Lebensmittelsicherheit und Produktkennzeichnung.",
        "Ich erkläre Risiken von Schadstoffen differenziert.",
        "Ich forme Konditionalsätze in präpositionale Ausdrücke um.",
      ],
      [
        ["die Lebensmittelsicherheit", "der Schutz vor gesundheitlichen Risiken durch Nahrung"],
        ["das Pestizid", "ein Mittel gegen Schädlinge in der Landwirtschaft"],
        ["der Schadstoff", "ein Stoff mit schädlicher Wirkung auf Mensch oder Umwelt"],
        ["das Biosiegel", "eine Kennzeichnung für kontrolliert ökologische Produktion"],
        ["der Verzehr", "das Essen oder Trinken eines Lebensmittels"],
        ["die Nahrungsmittelqualität", "die Gesamtheit wichtiger Eigenschaften eines Lebensmittels"],
        ["die Höchstgrenze", "der maximal erlaubte Wert"],
        ["unbedenklich", "nach aktuellem Wissen nicht gefährlich"],
      ],
      ["wenn oder falls … ↔ bei …", "unter der Voraussetzung, dass …"],
      "Bewerte ein Lebensmittel anhand von Herkunft, Kennzeichnung und möglichem Risiko.",
      "Schreibe eine Verbraucherinformation mit Bedingung, Empfehlung und Begründung.",
    ),
    profile(
      [
        "Ich kommentiere unterschiedliche Wellness-Angebote.",
        "Ich unterscheide Aussage, Einwand und Schlussfolgerung.",
        "Ich halte ein klar gegliedertes Kurzreferat.",
      ],
      [
        ["die Wellness", "Aktivitäten zur Förderung von Wohlbefinden und Entspannung"],
        ["der Ausgleich", "eine Tätigkeit, die Belastungen entgegenwirkt"],
        ["umstritten", "von verschiedenen Seiten sehr unterschiedlich beurteilt"],
        ["das Resümee", "eine knappe abschließende Zusammenfassung"],
        ["der Einwand", "ein begründeter Widerspruch gegen eine Aussage"],
        ["die Schlussfolgerung", "ein Ergebnis, das aus Informationen abgeleitet wird"],
        ["das Handout", "eine kurze schriftliche Begleitung zu einem Vortrag"],
        ["die Gedächtnishilfe", "ein Mittel, das beim Erinnern unterstützt"],
      ],
      ["Ein häufig genannter Einwand lautet …", "Daraus lässt sich schlussfolgern, dass …"],
      "Halte ein dreiminütiges Referat über ein Wellness-Angebot und reagiere auf einen Einwand.",
      "Erstelle ein einseitiges Handout mit Gliederung, Kernaussagen und Resümee.",
    ),
    review(
      "Gesund und munter",
      "Infinitiv- und Konditionalsätze",
      [
        ["die Ausdauer", "die Fähigkeit, eine Belastung lange durchzuhalten"],
        ["jemandem guttun", "eine positive Wirkung auf eine Person haben"],
        ["die Wirksamkeit", "das Ausmaß, in dem eine Behandlung wirkt"],
        ["nachweisen", "mit Daten oder Belegen eindeutig zeigen"],
        ["die Krankheitsprävention", "Maßnahmen zur Verhinderung von Krankheiten"],
        ["das Präventionsangebot", "eine konkrete Maßnahme zur Vorbeugung"],
        ["die Lebensmittelsicherheit", "der Schutz vor Risiken durch Nahrung"],
        ["unbedenklich", "nach aktuellem Wissen nicht gefährlich"],
      ],
    ),
  ],
  [
    profile(
      [
        "Ich verstehe zentrale Aussagen zu Humor und Komik.",
        "Ich erkläre, warum eine Situation komisch wirkt.",
        "Ich vergleiche unterschiedliche Reaktionen auf Humor.",
      ],
      [
        ["der Komiker", "eine Person, die beruflich humoristisch auftritt"],
        ["einen Platz vergeben", "einen verfügbaren Platz einer Person zuteilen"],
      ],
      ["Der Witz beruht darauf, dass …", "Was daran komisch oder ironisch wirkt, ist …"],
      "Erkläre die Wirkung eines Witzes oder Cartoons, ohne ihn wörtlich zu übersetzen.",
      "Schreibe etwa 80 Wörter über mögliche Grenzen des Humors.",
    ),
    profile(
      [
        "Ich diskutiere Vor- und Nachteile ständiger Erreichbarkeit.",
        "Ich gebe Aussagen anderer sprachlich abwechslungsreich wieder.",
        "Ich formuliere Regeln für eine gesunde Kommunikationskultur.",
      ],
      [
        ["die Erreichbarkeit", "die Möglichkeit, jederzeit kontaktiert zu werden"],
        ["die Kommunikationskultur", "gemeinsame Regeln und Gewohnheiten der Verständigung"],
        ["die Vereinbarkeit", "die Möglichkeit, mehrere Lebensbereiche miteinander zu verbinden"],
        ["das Dauerfeuer", "eine ununterbrochene Folge von Nachrichten oder Reizen"],
        ["die Sendepause", "eine bewusst eingelegte Unterbrechung der Kommunikation"],
        ["das Kommunikationsmanagement", "die geplante Steuerung von Informationsaustausch"],
        ["der Zugriff auf etwas", "die Möglichkeit, Daten oder Inhalte zu erreichen"],
        ["unverbindlich", "ohne feste Verpflichtung oder sichere Zusage"],
      ],
      ["Laut dem Bericht … / Dem Bericht zufolge …", "Er behauptet, er sei … / Er soll …"],
      "Entwickle eine Erreichbarkeitsregel für ein Team und begründe sie.",
      "Schreibe etwa 130 Wörter über ein Recht auf Nichterreichbarkeit.",
    ),
    profile(
      [
        "Ich erkenne verbale Angriffe und ihre Wirkung.",
        "Ich reagiere schnell, ruhig und sachlich auf Provokationen.",
        "Ich wähle eine passende Abwehrstrategie für die jeweilige Situation.",
      ],
      [
        ["die Schlagfertigkeit", "die Fähigkeit, schnell und treffend zu antworten"],
        ["die Provokation", "eine Äußerung, die bewusst eine Reaktion auslösen soll"],
        ["der Angriff", "eine aggressive verbale oder körperliche Handlung"],
        ["die Abwehrstrategie", "ein planvolles Vorgehen gegen einen Angriff"],
        ["kontern", "direkt mit einem passenden Gegenargument antworten"],
        ["der Angeber", "eine Person, die ihre Leistungen übertrieben präsentiert"],
        ["unverschämt", "grob und ohne angemessenen Respekt"],
        ["die Körperhaltung", "die Art, wie eine Person ihren Körper hält"],
      ],
      ["Das sehe ich anders, denn …", "Lassen Sie uns bitte sachlich bleiben."],
      "Reagiere auf fünf typische Provokationen aus Studium oder Beruf.",
      "Erstelle eine Tabelle mit Provokation, ungünstiger Reaktion und guter Reaktion.",
    ),
    profile(
      [
        "Ich fasse die Argumentation eines Fachtextes zum Spracherwerb zusammen.",
        "Ich kommentiere eine wissenschaftliche These mit Belegen und Beispielen.",
        "Ich forme Nominalstil und Verbalstil ineinander um.",
      ],
      [
        ["der Spracherwerb", "der Prozess, durch den eine Sprache erworben wird"],
        ["die Aneignung", "das aktive Erwerben von Wissen oder Fähigkeiten"],
        ["der Lernprozess", "die schrittweise Entwicklung von Wissen und Können"],
        ["implizit", "indirekt und nicht ausdrücklich formuliert"],
        ["explizit", "klar und ausdrücklich formuliert"],
        ["der Fachtext", "ein sachlicher Text für ein bestimmtes Fachgebiet"],
        ["die Abweichung", "ein Unterschied zu einer Norm oder Erwartung"],
        ["das Sprachvermögen", "die Fähigkeit, Sprache zu verstehen und zu verwenden"],
      ],
      ["aufgrund des … ↔ weil oder da …", "die Aneignung der Sprache ↔ sich die Sprache aneignen"],
      "Erkläre deinen eigenen Spracherwerb mit mindestens fünf Fachbegriffen.",
      "Schreibe einen Kommentar von etwa 150 Wörtern zu einer Methode des Sprachenlernens.",
    ),
    profile(
      [
        "Ich verstehe Positionen zu Dialekt und Standardsprache.",
        "Ich vergleiche Sprachformen differenziert und ohne Vorurteile.",
        "Ich schreibe einen strukturierten und überzeugenden Leserbrief.",
      ],
      [
        ["die Hochsprache", "eine überregionale und standardisierte Sprachform"],
        ["der Dialekt", "eine regional geprägte Sprachform"],
        ["die Einschaltquote", "der Anteil der Personen, die eine Sendung sehen"],
        ["sich zurechtfinden", "sich in einer neuen Situation orientieren können"],
        ["hervorheben", "etwas als besonders wichtig betonen"],
        ["das Hochdeutsch", "die standardisierte Form der deutschen Sprache"],
        ["der Regiolekt", "eine regionale Sprachform zwischen Dialekt und Standardsprache"],
        ["das Sprachgefühl", "das intuitive Empfinden für passenden Sprachgebrauch"],
      ],
      ["Einerseits …, andererseits …", "Besonders hervorzuheben ist, dass …"],
      "Begründe deine Haltung zu Dialekt in den Medien in zwei Minuten.",
      "Schreibe einen Leserbrief von etwa 170 Wörtern zum Thema Dialekt im Unterricht.",
    ),
    review(
      "Hast du Worte?",
      "Redewiedergabe sowie Nominal- und Verbalstil",
      [
        ["die Erreichbarkeit", "die Möglichkeit, jederzeit kontaktiert zu werden"],
        ["die Kommunikationskultur", "gemeinsame Regeln der Verständigung"],
        ["die Schlagfertigkeit", "die Fähigkeit, schnell und treffend zu antworten"],
        ["die Abwehrstrategie", "ein planvolles Vorgehen gegen einen Angriff"],
        ["der Spracherwerb", "der Prozess, durch den eine Sprache erworben wird"],
        ["die Aneignung", "das aktive Erwerben von Wissen oder Fähigkeiten"],
        ["der Regiolekt", "eine regionale Sprachform zwischen Dialekt und Standard"],
        ["das Sprachgefühl", "das intuitive Empfinden für passenden Sprachgebrauch"],
      ],
    ),
  ],
  [
    profile(
      [
        "Ich beschreibe ungewöhnliche Berufe und ihre Aufgaben.",
        "Ich ordne beruflichen Tätigkeiten passende Kompetenzen zu.",
        "Ich beurteile meine Eignung für eine Stelle und begründe sie.",
      ],
      [
        ["die Arbeitsweise", "die typische Art, wie eine Person arbeitet"],
        ["die Qualitätskontrolle", "die systematische Prüfung der Produktqualität"],
        ["der Rohstoff", "ein natürlicher Ausgangsstoff für die Produktion"],
        ["die Aufsicht", "die verantwortliche Kontrolle einer Tätigkeit"],
        ["sich auf eine Stelle bewerben", "Unterlagen für eine ausgeschriebene Arbeit einreichen"],
        ["die Lagerung", "die sachgerechte Aufbewahrung von Waren"],
        ["die Niederlassung", "ein Standort eines Unternehmens"],
        ["das Technologieunternehmen", "eine Firma, die technische Produkte entwickelt"],
      ],
      ["Für diesen Beruf ist … unerlässlich.", "Meine Stärke liegt darin, dass …"],
      "Präsentiere einen interessanten Beruf aus der Sicht einer Personalverantwortlichen.",
      "Erstelle ein kurzes Anforderungsprofil für deinen Wunschberuf.",
    ),
    profile(
      [
        "Ich verstehe und beurteile einen ungewöhnlichen Lebenslauf.",
        "Ich erkläre Lücken und berufliche Richtungswechsel glaubwürdig.",
        "Ich verwende Subjekt- und Objektsätze korrekt.",
      ],
      [
        ["die Vita", "eine kurze Darstellung des Lebens- und Berufswegs"],
        ["die Berufslaufbahn", "die gesamte Entwicklung im Berufsleben"],
        ["der Richtungswechsel", "eine deutliche Änderung des bisherigen Weges"],
        ["der Werdegang", "die persönliche schulische und berufliche Entwicklung"],
        ["lückenlos", "vollständig und ohne zeitliche Unterbrechung"],
        ["die Neuorientierung", "die Entscheidung für eine neue berufliche Richtung"],
        ["der Stolperstein", "eine Schwierigkeit, die den Fortschritt behindert"],
        ["plausibel", "logisch und glaubwürdig"],
      ],
      ["Es ist ratsam, … zu …", "Dass der Lebenslauf Lücken enthält, ist …"],
      "Stelle deinen Werdegang vor und erläutere einen Richtungswechsel.",
      "Schreibe etwa 140 Wörter über deinen Weg und deine wichtigsten Kompetenzen.",
    ),
    profile(
      [
        "Ich vergleiche Hochschulstudium und Berufsausbildung.",
        "Ich stelle in einem Beratungsgespräch präzise Rückfragen.",
        "Ich wäge Alternativen anhand klarer Kriterien ab.",
      ],
      [
        ["die Berufspraxis", "praktische Erfahrung in einem Beruf"],
        ["die Aufstiegschance", "eine Möglichkeit, beruflich eine höhere Position zu erreichen"],
        ["die Zulassungsvoraussetzung", "eine Bedingung für die Aufnahme in einen Bildungsgang"],
        ["die Eignung", "die passenden Fähigkeiten für eine Aufgabe"],
        ["abwägen", "Vor- und Nachteile sorgfältig vergleichen"],
        ["der Berufsschulabschluss", "der Abschluss einer beruflichen Schule"],
        ["die Doppelbelastung", "die gleichzeitige Belastung durch zwei große Aufgaben"],
        ["das Zeitmanagement", "die planvolle Einteilung der verfügbaren Zeit"],
      ],
      ["Für oder gegen … spricht …", "Unter Berücksichtigung von … würde ich … vorziehen."],
      "Berate eine Person, die zwischen Ausbildung und Studium wählen muss.",
      "Schreibe einen strukturierten Vergleich beider Bildungswege.",
    ),
    profile(
      [
        "Ich fasse einen Artikel über Multitasking zusammen.",
        "Ich verbinde Behauptungen, Belege und Folgen logisch.",
        "Ich verwende weiterführende Nebensätze.",
      ],
      [
        ["das Multitasking", "das gleichzeitige Bearbeiten mehrerer Aufgaben"],
        ["die Ablenkung", "etwas, das die Konzentration unterbricht"],
        ["die Zeitfalle", "eine Tätigkeit, die unerwartet viel Zeit kostet"],
        ["die Ressource", "ein verfügbares Mittel zur Erreichung eines Ziels"],
        ["bewältigen", "eine schwierige Aufgabe erfolgreich erledigen"],
        ["der Dauerstress", "eine länger anhaltende starke Belastung"],
        ["die Gleichzeitigkeit", "das Stattfinden mehrerer Vorgänge zur selben Zeit"],
        ["die Unterbrechung", "eine Pause in einem laufenden Vorgang"],
      ],
      ["…, weswegen … / …, was dazu führt, dass …", "sich auf eine Aussage beziehen"],
      "Berichte über eine kurze Mono-Tasking-Erfahrung und bewerte sie.",
      "Schreibe eine Zusammenfassung von etwa 130 Wörtern zum Thema Multitasking.",
    ),
    profile(
      [
        "Ich bewerte wichtige Soft Skills und begründe ihre Rangfolge.",
        "Ich höre aktiv zu und gebe konkretes Feedback.",
        "Ich strukturiere einen Vortrag mit klaren Übergängen.",
      ],
      [
        ["die Eigeninitiative", "selbstständiges Handeln ohne äußere Aufforderung"],
        ["das Einfühlungsvermögen", "die Fähigkeit, Gefühle anderer nachzuvollziehen"],
        ["das Durchsetzungsvermögen", "die Fähigkeit, berechtigte Ziele konsequent zu vertreten"],
        ["die Zuverlässigkeit", "die Eigenschaft, Absprachen sicher einzuhalten"],
        ["der Schreibplan", "eine Gliederung zur Vorbereitung eines Textes"],
        ["die Kritikfähigkeit", "die Fähigkeit, Kritik anzunehmen und sinnvoll zu nutzen"],
        ["die Führungskompetenz", "die Fähigkeit, Menschen und Aufgaben wirksam zu leiten"],
        ["die Priorität", "ein Ziel oder eine Aufgabe mit besonderer Dringlichkeit"],
      ],
      ["An erster Stelle steht … / Großen Wert lege ich auf …", "Ich möchte nun zum nächsten Punkt übergehen."],
      "Halte einen dreiminütigen Vortrag über einen besonders wichtigen Soft Skill.",
      "Erstelle einen Schreibplan und anschließend einen Text von etwa 180 Wörtern über Teamarbeit.",
    ),
    review(
      "An die Arbeit!",
      "Subjekt- und Objektsätze sowie weiterführende Nebensätze",
      [
        ["die Berufslaufbahn", "die gesamte Entwicklung im Berufsleben"],
        ["die Neuorientierung", "die Entscheidung für eine neue berufliche Richtung"],
        ["die Berufspraxis", "praktische Erfahrung in einem Beruf"],
        ["die Doppelbelastung", "die gleichzeitige Belastung durch zwei große Aufgaben"],
        ["die Ablenkung", "etwas, das die Konzentration unterbricht"],
        ["bewältigen", "eine schwierige Aufgabe erfolgreich erledigen"],
        ["das Einfühlungsvermögen", "die Fähigkeit, Gefühle anderer nachzuvollziehen"],
        ["die Kritikfähigkeit", "die Fähigkeit, Kritik sinnvoll zu nutzen"],
      ],
    ),
  ],
];

const chapters = [
  chapterGroupA[0],
  chapterGroupB[3],
  chapterGroupB[4],
  chapterGroupB[0],
  chapterGroupB[1],
  chapterGroupB[2],
  chapterGroupA[1],
  chapterGroupA[2],
  chapterGroupA[3],
  chapterGroupA[4],
];

export const moduleStudyProfiles = Object.fromEntries(
  chapters.flatMap((chapter, chapterIndex) => chapter.map(
    (study, moduleIndex) => ["k" + (chapterIndex + 1) + "-m" + moduleIndex, study],
  )),
);

export function getModuleStudyProfile(id) {
  return moduleStudyProfiles[id] || null;
}
